# Generated by Django 5.2.3 on 2026-04-23 12:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_user_customer_username_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnpaidAmount',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_amounts', to='store.customer')),
            ],
            options={
                'db_table': 'unpaid_amounts',
                'unique_together': {('customer', 'month')},
            },
        ),
    ]
